Back to an older version of ci-maven.yml

diff --git a/.github/workflows/ci-maven.yml b/.github/workflows/ci-maven.yml
--- a/.github/workflows/ci-maven.yml
+++ b/.github/workflows/ci-maven.yml
@@ -34,7 +34,7 @@ jobs:
           cache: maven
 
       - name: Run the Maven verify phase
-        run: mvn --batch-mode --update-snapshots -Dsnyk.skip verify
+        run: mvn --batch-mode -Dsnyk.skip verify
 
       - run: mkdir staging && cp target/*.jar staging
       - uses: actions/upload-artifact@v4
@@ -46,10 +46,14 @@ jobs:
 #        if: success() || failure()
 #        uses: ScaCap/action-surefire-report@v1.8.0
 
-      - uses: dorny/test-reporter@v1.9.1
-        if: success() || failure()
-        with:
-          name: Junit Test Report
-          path: 'target/surefire-reports/*.xml'
-          reporter: java-junit
-          fail-on-error: true
+#      - uses: dorny/test-reporter@v1.9.1
+#        if: success() || failure()
+#        with:
+#          name: Junit Test Report
+#          path: 'target/surefire-reports/*.xml'
+#          reporter: java-junit
+#          fail-on-error: true
+#
+      - name: Publish container image to Docker Hub
+        id: publish
+        run: DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }} mvn --batch-mode clean compile jib:build
