Uncomment asserts tests that were failing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,16 +30,16 @@ jobs:
         uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
 
       - name: Build with Gradle
-        run: ./gradlew build
+        run: ./gradlew clean build
 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4.3.1
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: '**/build/test-results/test/TEST-*.xml'
-          detailed_summary: true
-          include_passed: true
-#          flaky_summary: true
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@v4.3.1
+#        if: success() || failure() # always run even if the previous step fails
+#        with:
+#          report_paths: '**/build/test-results/test/TEST-*.xml'
+#          detailed_summary: true
+#          include_passed: true
+##          flaky_summary: true
 
       - name: Report
         uses: dorny/test-reporter@v1.9.1
